apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-2
  labels:
    app: frontend-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-2
  template:
    metadata:
      labels:
        app: frontend-2
    spec:
      containers:
      - name: frontend-2
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-2-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-2-html
data:
  index.html: |
    <html>
    <head><title>Frontend 2</title></head>
    <body style="font-family: Arial; text-align:center; margin-top:50px;">
      <h1>ðŸ”¥ Frontend 2 on EKS</h1>
      <p>Deployed using Argo CD</p>
    </body>
    </html>
